##配置你的账号密码数据源，修改后未生效重启idea即可
spring:
  datasource:
    url: jdbc:mysql://service.cf:3308/seer-default?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: root
    password: HBQ521521cf*
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.generator.model

server:
  port: 8081