##配置你的账号密码数据源
spring:
  datasource:
    url: -------
    username: -------
    password: -------
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.generator.model

server:
  port: 8081
