##配置你的账号密码数据源，修改后未生效可重启idea
spring:
  datasource:
    url: jdbc:mysql://"ip:端口"/"数据库"?useUnicode=true&characterEncoding=UTF-8
    username: "你的账号"
    password: "你的密码"
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.generator.model

server:
  port: 8081
