##配置你的账号密码数据源，修改后未生效重启idea即可
spring:
  datasource:
    url: jdbc:mysql://service.cf:3306/cms-plus?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: HBQ521521cf*
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.generator.model

server:
  port: 8081